theme: jekyll-theme-cayman
title: Iain K. MacLeod
description: He/Him | Applier of words, pictures, and videos since logging onto CompuServe in 1993. Natural collaborator and BS detector.
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
