url: "https://iain.ca"
timezone: "America/Halifax"
remote_theme: pages-themes/jekyll-theme-primer
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
title: Iain K. MacLeod
description: He/Him | Born to be mild. Great-great-great grandnephew of Angus “Giant” MacAskill. Worked skateboard check at 1994 Gobblefest.
include: [".well-known"]
show_downloads: false
google_analytics: G-59HSMGKJRP

exclude:
  - node_modules
  - script

sass:
  style: :compressed

github:
  private: false
  license:
    name:
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/boostventilator/boostventilator.github.io"
